# Config file for automatic testing at travis-ci.org
language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - 3.7
services: postgresql
install: pip install -r requirements/dev.txt
before_script:
  - psql -c 'create database arc_designs;' -U postgres
  - export FLASK_APP="$TRAVIS_BUILD_DIR/manage.py"
  - export FLASK_DEBUG=1

script: flask test
after_success:
  - coveralls
