"""empty message

Revision ID: 95f403359cf5
Revises: 47c30d5cb283
Create Date: 2019-08-21 08:35:26.468566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95f403359cf5'
down_revision = '47c30d5cb283'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('addedAt', sa.DateTime(), nullable=False))
    op.add_column('cart', sa.Column('author_id', sa.Integer(), nullable=False))
    op.add_column('cart', sa.Column('post_id', sa.Integer(), nullable=False))
    op.drop_constraint('cart_product_fkey', 'cart', type_='foreignkey')
    op.drop_constraint('cart_username_fkey', 'cart', type_='foreignkey')
    op.create_foreign_key(None, 'cart', 'users', ['author_id'], ['id'])
    op.create_foreign_key(None, 'cart', 'posts', ['post_id'], ['id'])
    op.drop_column('cart', 'product')
    op.drop_column('cart', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('username', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('cart', sa.Column('product', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'cart', type_='foreignkey')
    op.drop_constraint(None, 'cart', type_='foreignkey')
    op.create_foreign_key('cart_username_fkey', 'cart', 'users', ['username'], ['id'])
    op.create_foreign_key('cart_product_fkey', 'cart', 'posts', ['product'], ['id'])
    op.drop_column('cart', 'post_id')
    op.drop_column('cart', 'author_id')
    op.drop_column('cart', 'addedAt')
    # ### end Alembic commands ###
